dbt/include/spark_cde/macros/adapters.sql
dbt/include/spark_cde/macros/materializations/incremental/incremental.sql
dbt/include/spark_cde/macros/materializations/incremental/strategies.sql
dbt/include/spark_cde/macros/materializations/seed.sql
dbt/include/spark_cde/macros/materializations/snapshot.sql
dbt/include/spark_cde/macros/materializations/table.sql
dbt/include/spark_cde/macros/materializations/view.sql
dbt/include/spark_cde/macros/utils/any_value.sql
dbt/include/spark_cde/macros/utils/assert_not_null.sql
dbt/include/spark_cde/macros/utils/bool_or.sql
dbt/include/spark_cde/macros/utils/concat.sql
dbt/include/spark_cde/macros/utils/dateadd.sql
dbt/include/spark_cde/macros/utils/datediff.sql
dbt/include/spark_cde/macros/utils/listagg.sql
dbt/include/spark_cde/macros/utils/split_part.sql

rename macro names to reflect adapter name change to spark_cde

rename macros to reflect adapter name change to spark_cde

---

tests/unit/test_adapter.py
tests/unit/test_column.py

update imports in tests/ directory to reflect adapter name change to spark_cde

update imports in tests/ to reflect adapter name change to spark_cde

---

dbt/adapters/spark_cde/connections.py

integrate cde api adapter call into connections.py which introduces method=cde in dbt profiles

add cde api adapter call in connections.py 

---

dbt/adapters/spark_cde/connections.py

profile variables user and password required for cde api connection are added to connections.py

add missing profile variables in connections.py

---

tests/conftest.py

add a test method for spark_cde in tests/conftest.py and make it default.

add a test method for spark_cde

---

dbt/adapters/spark_cde/cdeapisession.py

extract schema datatype based on first row of sql output. currently only string, number and boolean types are inferred. defaults to string.

extract schema datatype based on first row of the sql output.

---

dbt/adapters/spark_cde/.env
dbt/adapters/spark_cde/adaptertimer.py
dbt/adapters/spark_cde/cdeapisession.py

- Testing for capturing each methods timings
- Testing for successful session being logged
- Testing for failed run being logged

Add profiling for each method called in CDEAPISession

---

dbt/adapters/spark_cde/cdeapisession.py

No change in functionality. Changed method names to be consistent
Tested by performing a succesful dbt run

Changes method names to be uniform(follow snake style)

---

dbt/adapters/spark_cde/cdeapisession.py
requirements.txt

No new logic introduced. Code cleanup to 
- remove unused imports and methods
- any reference to adapter timer
- fix typos 
Tested by doing a dbt run.

Remove timer and unused methods

---

dbt/adapters/spark_cde/cdeapisession.py

Testing 
**incorrect username/password**
Connection:
host: https://tx4lvf8t.cde-bhs8thz9.ciadev.cna2-sx9y.cloudera.site/dex/api/v1
port: 443
cluster: None
endpoint: None
schema: dbtbmstest
organization: 0
Http Error:  401 Client Error: Unauthorized for url: https://service.cde-bhs8thz9.ciadev.cna2-sx9y.cloudera.site/gateway/authtkn/knoxtoken/api/v1/token
Connection test: [ERROR]
==============================================
**incorrect authpoint**
Connection:
host: https://tx4lvf8t.cde-bhs8thz9.ciadev.cna2-sx9y.cloudera.site/dex/api/v1/
port: 443
cluster: None
endpoint: None
schema: dbtbmstest
organization: 0
Connection Error : HTTPSConnectionPool(host='service.cde-bhs8thz9.ciadev.cna2-sx9y.cloudera.site1', port=443): Max retries exceeded with url: /gateway/authtkn/knoxtoken/api/v1/token …

Dbt debug changes

---

dbt/adapters/spark_cde/__version__.py
setup.py

Updating version numbers that was missed for last 2 releases.

boost version numbers for todays release

---

dbt/adapters/spark_cde/__version__.py
setup.py

Bump version for pypi release 1.1.4
N/A
N/A

bump version for pypi release

---

.env_example

Fix a typo in .env_example
NA
NA

fix typo for .env_example

---

dbt/adapters/spark_cde/cloudera_tracking.py
dbt/adapters/spark_cde/connections.py

Added cloudera tracking library for instrumentation
Removed old tracking code
Internal ticket DBT-482
Tested that dbt still works

Add cloudera tracking library+ cleanup old tracking

---

dbt/adapters/spark_cde/cdeapisession.py
dbt/adapters/spark_cde/connections.py

Add an optional profile flag verify_ssl_certificate allowing to switch on/off ssl certificate verification.
Default value of this flag in True, meaning ssl certificate will be verified by default.
See DBT-464, DBT-184 (Internal)
In a valid dbt-spark-cde profile, add: verify_ssl_certificate: false (to disable ssl certificate verification, default value being true), the dbt debug should succeed.

add profile variable to switch on/off ssl certificate verification

---

dbt/adapters/spark_cde/connections.py

Fetch profile related instrumentation  
project_name: string
target_name: string
no_of_threads: number
Fixed merge conflicts on previous pr
DBT-484

Added instrumentation to fetch profile info

---

dbt/adapters/spark_cde/__version__.py
setup.py

version bump for pypi release

---

dbt/adapters/spark_cde/cloudera_tracking.py
dbt/adapters/spark_cde/connections.py

Description:
Adding instrumentation for dbt deployment environment variables
Test output
Non CML
\"dbt_version\": \"1.1.2\", \"dbt_adapter\": \"spark_cde-1.1.6\", \"dbt_deployment_env\": \"\", \"project_name\": \"dbt_spark_cde_demo\", \"target_name\": \"cloudera_cia_dev_cde\", \"no_of_threads\": 4}","created_at":"2022-10-27T13:18:45.487Z"}
CML
"dbt_version\": \"1.1.2\", \"dbt_adapter\": \"spark_cde-1.1.6\", \"dbt_deployment_env\": \"{ \\\"env\\\":\\\"cml\\\", \\\"version\\\":\\\"1.1.15\\\",\\\"description\\\":\\\"This runtime includes DBT upgraded packages dbt-impala=1.1.4,dbt-hive=1.1.4,dbt-spark-cde=1.1.4,dbt-spark-livy=1.1.5\\\",\\\"edition\\\":\\\"dbt custom runtime\\\",\\\"image\\\":\\\"test-image\\\"}\", \"project_name\": \"dbt_spark_cde_demo\", \"target_name\": …

Add dbt deployment environment instrumentation

---

dbt/adapters/spark_cde/__version__.py
setup.py

Updating dbt-spark-cde version to 1.1.7

bump version for release

---

dbt/adapters/spark_cde/impl.py

Fix version reported for warehouse for instrumentation to supported value, avoiding additional call so that performance is improved.

fix version reported for warehouse for instrumentation to supported value

---

dbt/adapters/spark_cde/cdeapisession.py

Enable the following job submission parameters to be controlled via profiles.yml file using cde_session_parameters:
<pre>
cde_session_parameters:
dbt.cde.job_timeout: 500 (default 900)
dbt.cde.poll_wait: 15 (default 30)
dbt.cde.log_wait: 20 (default 40) 
</pre>
All time parameters are in seconds.

enable user controlled cde job submission parameters

---

dbt/adapters/spark_cde/cdeapisession.py
dbt/adapters/spark_cde/connections.py

Add more descriptive job name that makes it possible to more clearly identify the model for which the cde job is being executed. 
Sample jobs names are generated for a sample dbt project:

add node_id string to job_id for cde job
